# Form implementation generated from reading ui file 'converter.ui'
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 550)
        MainWindow.setMinimumSize(QtCore.QSize(650, 550))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 550))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #667eea, stop:1 #764ba2);\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"    margin: 5px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #f0f0f0;\n"
"    color: #333;\n"
"    padding: 12px 20px;\n"
"    margin: 3px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    border: 1px solid #5a4acd;\n"
"}\n"
"\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #e0e0ff;\n"
"    border: 1px solid #6a5acd;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.physical_tab = QtWidgets.QWidget()
        self.physical_tab.setObjectName("physical_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.physical_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.physical_tab)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.category_combo = QtWidgets.QComboBox(parent=self.physical_tab)
        self.category_combo.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 12px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #6a5acd;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"    selection-background-color: #6a5acd;\n"
"}")
        self.category_combo.setObjectName("category_combo")
        self.category_combo.addItem("")
        self.category_combo.addItem("")
        self.category_combo.addItem("")
        self.category_combo.addItem("")
        self.category_combo.addItem("")
        self.category_combo.addItem("")
        self.category_combo.addItem("")
        self.horizontalLayout.addWidget(self.category_combo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.physical_tab)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.from_unit_combo = QtWidgets.QComboBox(parent=self.physical_tab)
        self.from_unit_combo.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 12px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 4px solid #6a5acd;\n"
"}")
        self.from_unit_combo.setObjectName("from_unit_combo")
        self.verticalLayout_3.addWidget(self.from_unit_combo)
        self.from_value_edit = QtWidgets.QLineEdit(parent=self.physical_tab)
        self.from_value_edit.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #6a5acd;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff6b6b;\n"
"    background-color: #fff5f5;\n"
"}")
        self.from_value_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.from_value_edit.setObjectName("from_value_edit")
        self.verticalLayout_3.addWidget(self.from_value_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.swap_units_btn = QtWidgets.QPushButton(parent=self.physical_tab)
        self.swap_units_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.swap_units_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ff6b6b;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5252;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e74c3c;\n"
"}")
        self.swap_units_btn.setObjectName("swap_units_btn")
        self.horizontalLayout_2.addWidget(self.swap_units_btn)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.physical_tab)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.to_unit_combo = QtWidgets.QComboBox(parent=self.physical_tab)
        self.to_unit_combo.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 12px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 4px solid #6a5acd;\n"
"}")
        self.to_unit_combo.setObjectName("to_unit_combo")
        self.verticalLayout_4.addWidget(self.to_unit_combo)
        self.to_value_edit = QtWidgets.QLineEdit(parent=self.physical_tab)
        self.to_value_edit.setStyleSheet("QLineEdit {\n"
"    background-color: #f8f9fa;\n"
"    border: 2px solid #28a745;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #e8f5e8;\n"
"    color: #27ae60;\n"
"}")
        self.to_value_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.to_value_edit.setReadOnly(True)
        self.to_value_edit.setObjectName("to_value_edit")
        self.verticalLayout_4.addWidget(self.to_value_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.physical_tab, "")
        self.currency_tab = QtWidgets.QWidget()
        self.currency_tab.setObjectName("currency_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.currency_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.currency_tab)
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.last_update_label = QtWidgets.QLabel(parent=self.currency_tab)
        self.last_update_label.setStyleSheet("QLabel {\n"
"    background-color: #ffa726;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"}")
        self.last_update_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.last_update_label.setObjectName("last_update_label")
        self.horizontalLayout_4.addWidget(self.last_update_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.update_rates_btn = QtWidgets.QPushButton(parent=self.currency_tab)
        self.update_rates_btn.setStyleSheet("QPushButton {\n"
"    background-color: #17a2b8;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 15px;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #138496;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #117a8b;\n"
"}")
        self.update_rates_btn.setObjectName("update_rates_btn")
        self.horizontalLayout_4.addWidget(self.update_rates_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.currency_tab)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.from_currency_combo = QtWidgets.QComboBox(parent=self.currency_tab)
        self.from_currency_combo.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 4px solid #6a5acd;\n"
"}")
        self.from_currency_combo.setObjectName("from_currency_combo")
        self.from_currency_combo.addItem("")
        self.from_currency_combo.addItem("")
        self.from_currency_combo.addItem("")
        self.from_currency_combo.addItem("")
        self.from_currency_combo.addItem("")
        self.from_currency_combo.addItem("")
        self.verticalLayout_6.addWidget(self.from_currency_combo)
        self.from_currency_edit = QtWidgets.QLineEdit(parent=self.currency_tab)
        self.from_currency_edit.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    selection-background-color: #6a5acd;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff6b6b;\n"
"    background-color: #fff5f5;\n"
"}")
        self.from_currency_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.from_currency_edit.setObjectName("from_currency_edit")
        self.verticalLayout_6.addWidget(self.from_currency_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.swap_currency_btn = QtWidgets.QPushButton(parent=self.currency_tab)
        self.swap_currency_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.swap_currency_btn.setStyleSheet("QPushButton {\n"
"    background-color: #ff6b6b;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ff5252;\n"
"    transform: scale(1.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e74c3c;\n"
"}")
        self.swap_currency_btn.setObjectName("swap_currency_btn")
        self.horizontalLayout_3.addWidget(self.swap_currency_btn)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.currency_tab)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: #6a5acd;\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 11px;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.to_currency_combo = QtWidgets.QComboBox(parent=self.currency_tab)
        self.to_currency_combo.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    border: 2px solid #6a5acd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 4px solid #6a5acd;\n"
"}")
        self.to_currency_combo.setObjectName("to_currency_combo")
        self.to_currency_combo.addItem("")
        self.to_currency_combo.addItem("")
        self.to_currency_combo.addItem("")
        self.to_currency_combo.addItem("")
        self.to_currency_combo.addItem("")
        self.to_currency_combo.addItem("")
        self.verticalLayout_7.addWidget(self.to_currency_combo)
        self.to_currency_edit = QtWidgets.QLineEdit(parent=self.currency_tab)
        self.to_currency_edit.setStyleSheet("QLineEdit {\n"
"    background-color: #f8f9fa;\n"
"    border: 2px solid #28a745;\n"
"    border-radius: 8px;\n"
"    padding: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #e8f5e8;\n"
"    color: #27ae60;\n"
"}")
        self.to_currency_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.to_currency_edit.setReadOnly(True)
        self.to_currency_edit.setObjectName("to_currency_edit")
        self.verticalLayout_7.addWidget(self.to_currency_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.tabWidget.addTab(self.currency_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("QStatusBar {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    font-size: 11px;\n"
"}")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Универсальный конвертер"))
        self.label.setText(_translate("MainWindow", "Категория:"))
        self.category_combo.setItemText(0, _translate("MainWindow", "📏 Длина"))
        self.category_combo.setItemText(1, _translate("MainWindow", "⚖️ Масса"))
        self.category_combo.setItemText(2, _translate("MainWindow", "🌡️ Температура"))
        self.category_combo.setItemText(3, _translate("MainWindow", "🚀 Скорость"))
        self.category_combo.setItemText(4, _translate("MainWindow", "📐 Площадь"))
        self.category_combo.setItemText(5, _translate("MainWindow", "🧪 Объем"))
        self.category_combo.setItemText(6, _translate("MainWindow", "⏰ Время"))
        self.label_2.setText(_translate("MainWindow", "Из:"))
        self.from_value_edit.setPlaceholderText(_translate("MainWindow", "Введите значение..."))
        self.swap_units_btn.setText(_translate("MainWindow", "⇄"))
        self.label_3.setText(_translate("MainWindow", "В:"))
        self.to_value_edit.setPlaceholderText(_translate("MainWindow", "Результат..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.physical_tab), _translate("MainWindow", "📏 Физические величины"))
        self.label_4.setText(_translate("MainWindow", "Курсы обновлены:"))
        self.last_update_label.setText(_translate("MainWindow", "Не обновлялось"))
        self.update_rates_btn.setText(_translate("MainWindow", "🔄 Обновить курсы"))
        self.label_5.setText(_translate("MainWindow", "Из валюты:"))
        self.from_currency_combo.setItemText(0, _translate("MainWindow", "🇺🇸 USD - Доллар США"))
        self.from_currency_combo.setItemText(1, _translate("MainWindow", "🇪🇺 EUR - Евро"))
        self.from_currency_combo.setItemText(2, _translate("MainWindow", "🇷🇺 RUB - Российский рубль"))
        self.from_currency_combo.setItemText(3, _translate("MainWindow", "🇬🇧 GBP - Фунт стерлингов"))
        self.from_currency_combo.setItemText(4, _translate("MainWindow", "🇯🇵 JPY - Японская иена"))
        self.from_currency_combo.setItemText(5, _translate("MainWindow", "🇨🇳 CNY - Китайский юань"))
        self.from_currency_edit.setPlaceholderText(_translate("MainWindow", "Введите сумму..."))
        self.swap_currency_btn.setText(_translate("MainWindow", "⇄"))
        self.label_6.setText(_translate("MainWindow", "В валюту:"))
        self.to_currency_combo.setItemText(0, _translate("MainWindow", "🇷🇺 RUB - Российский рубль"))
        self.to_currency_combo.setItemText(1, _translate("MainWindow", "🇺🇸 USD - Доллар США"))
        self.to_currency_combo.setItemText(2, _translate("MainWindow", "🇪🇺 EUR - Евро"))
        self.to_currency_combo.setItemText(3, _translate("MainWindow", "🇬🇧 GBP - Фунт стерлингов"))
        self.to_currency_combo.setItemText(4, _translate("MainWindow", "🇯🇵 JPY - Японская иена"))
        self.to_currency_combo.setItemText(5, _translate("MainWindow", "🇨🇳 CNY - Китайский юань"))
        self.to_currency_edit.setPlaceholderText(_translate("MainWindow", "Результат..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.currency_tab), _translate("MainWindow", "💱 Конвертер валют"))
